### ISSUE TITLE
debuild errors

### ISSUE THREAD

**Issue by hellocatfood** [pd-l2ork/pd#22]
I'm attempting to compile pd-l2ork on Ubuntu 15:04 and make a deb file using instructions found at https://github.com/pd-l2ork/pd/blob/master/debuild/Makefile

After running `make deb` I get the following errors

dpkg-source: info: building pd-l2ork using existing
./pd-l2ork_0.42.6+git20150430+1514.orig-Gem.tar.gz
./pd-l2ork_0.42.6+git20150430+1514.orig-wiringPi.tar.gz
./pd-l2ork_0.42.6+git20150430+1514.orig.tar.gz
dpkg-source: warning: ignoring deletion of file
l2ork_addons/cwiid/wmgui/wmgui.glade.bak, use --include-removal to
override
dpkg-source: warning: ignoring deletion of file
l2ork_addons/cwiid/wmgui/wmgui.gladep.bak, use --include-removal to
override
dpkg-source: info: local changes detected, the modified files are:
 pd-l2ork-0.42.6+git20150430+1514/externals/Makefile
 pd-l2ork-0.42.6+git20150430+1514/externals/iem16/src/Makefile
 pd-l2ork-0.42.6+git20150430+1514/externals/moocow/extended/Makefile
dpkg-source: error: aborting due to unexpected upstream changes, see
/tmp/pd-l2ork_0.42.6+git20150430+1514-1.diff.q3GUr0
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-buildpackage: error: dpkg-source -b
pd-l2ork-0.42.6+git20150430+1514 gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
Makefile:67: recipe for target 'deb' failed
make: *** [deb] Error 29

The contents of the file that it refers to can be found here: http://pastebin.com/nLTq0wAj

**Comment by pd-l2ork** [comment]
I believe that is a deprecated build process. Please use build instructions
provided at http://l2ork.music.vt.edu/main/?page_id=56 and look for the
"building from source" found towards the bottom of the page. HTH

I'm attempting to compile pd-l2ork on Ubuntu 15:04 and make a deb file
using instructions found at
https://github.com/pd-l2ork/pd/blob/master/debuild/Makefile

After running make deb I get the following errors

dpkg-source: info: building pd-l2ork using existing
./pd-l2ork_0.42.6+git20150430+1514.orig-Gem.tar.gz
./pd-l2ork_0.42.6+git20150430+1514.orig-wiringPi.tar.gz
./pd-l2ork_0.42.6+git20150430+1514.orig.tar.gz
dpkg-source: warning: ignoring deletion of file
l2ork_addons/cwiid/wmgui/wmgui.glade.bak, use --include-removal to
override
dpkg-source: warning: ignoring deletion of file
l2ork_addons/cwiid/wmgui/wmgui.gladep.bak, use --include-removal to
override
dpkg-source: info: local changes detected, the modified files are:
pd-l2ork-0.42.6+git20150430+1514/externals/Makefile
pd-l2ork-0.42.6+git20150430+1514/externals/iem16/src/Makefile
pd-l2ork-0.42.6+git20150430+1514/externals/moocow/extended/Makefile
dpkg-source: error: aborting due to unexpected upstream changes, see
/tmp/pd-l2ork_0.42.6+git20150430+1514-1.diff.q3GUr0
dpkg-source: info: you can integrate the local changes with dpkg-source
--commit
dpkg-buildpackage: error: dpkg-source -b
pd-l2ork-0.42.6+git20150430+1514 gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
Makefile:67: recipe for target 'deb' failed
make: *** [deb] Error 29

The contents of the file that it refers to can be found here:
http://pastebin.com/nLTq0wAj

—
Reply to this email directly or view it on GitHub
<https://github.com/pd-l2ork/pd/issues/22>.

**Comment by pd-l2ork** [comment]
Forgot to mention, unless this is Albert's addition for launchpad PPA build
process.

**Comment by hellocatfood** [comment]
This is in response to Albert's addition for the launchpad PPA build. I believe I have all dependencies installed so not sure what is happening

**Comment by pd-l2ork** [comment]
Try using latest git snapshot and building as per instructions on L2Ork's website. I just updated the build process to make it hopefully fully compatible with Ubuntu 14.04. HTH

**Comment by agraef** [comment]
Just for the record, this was also discussed on the mailing list and I provided a solution there. It's actually an issue with debuild which can be solved easily. So not a pd-l2ork bug. :)

**Comment by pd-l2ork** [comment]
On 06/19/2015 11:24 PM, Albert Graef wrote:
>
> Just for the record, this was also discussed on the mailing list and I 
> provided a solution there. It's actually an issue with debuild which 
> can be solved easily. So not a pd-l2ork bug. :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/22#issuecomment-113648572>.
>
Great, many thanks, Albert!
