### ISSUE TITLE
warning messages while opening and closing a patch

### ISSUE THREAD

**Issue by nicopan** [pd-l2ork/pd#28]
Hi, launching pd-l2ork in a terminal, and loading a patch, I'm getting a lot of errors like these:

> in sys_gui .x26b7330.c coords .x26b7330.t1af4ecd0R 714 235 740 235 736 239 736 249 740 253 714 253 714 235
> invalid command name ".x26b7330.c"

> in sys_gui .x26b7330.c coords .x26b7330.t1af52cc0i0 414 235 421 237
> invalid command name ".x26b7330.c"

> in sys_gui .x603d670.c raise all_cords
> invalid command name ".x603d670.c"

The patch seems to work correctly, but I'd like to know what's the problem, or how to debug it.

   Thanks!

**Comment by pd-l2ork** [comment]
Nothing you should immediately worry about. We just expose any and all
possible invalid commands by printing them out so that we can track down
problems like this. This is a benign problem and it should not affect the
bottom line operability of your patch. That said, if you can send me a
simplified version of the patch that manifests this issue it will help us
track down the problem. Hope this helps!

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
Ico.bukvic.net

**Comment by nicopan** [comment]
Hi Ico, thanks for the quick reply.
[Here](http://nicolapandini.damai.it/tmp/sc-elefunk.pd) you can get a patch that produces some warnings.
I think that the problem may be inside one of the "bass-line" subpatches.

cheers

   Nicola

**Comment by pd-l2ork** [comment]
Thank you. Lemme investigate when I get a chance.

Best,

Ico

**Comment by pd-l2ork** [comment]
On 10/05/2015 10:59 AM, Nicola Pandini wrote:
>
> Hi Ico, thanks for the quick reply.
> Here <http://nicolapandini.damai.it/tmp/sc-elefunk.pd> you can get a 
> patch that produces some warnings.
> I think that the problem may be inside one of the "bass-line" subpatches.
>
> cheers
>
> Nicola
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/28#issuecomment-145558728>.
>
Nicola, I just committed a fix for this bug. It will be included in the 
next release. If you need it sooner, you can always build your own 
version by following instructions provided on the website. HTH

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
DISIS, L2Ork
Virginia Tech
School of Performing Arts - 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.music.vt.edu
l2ork.music.vt.edu
