### ISSUE TITLE
Midi in and out wont work in L2ork

### ISSUE THREAD

**Issue by arpeggio1234** [pd-l2ork/pd#39]
Just discovered this great program for my Linux laptop to build.
I am a great fan of Pd and Max/msp but choose Pd because of the open source thing.
So now i use L2ork and it works great except the MIDI part wont work.
I installed the libraries and after that the Burrito installer,
I see the Midi interface in the preferences and i connect but it does not respond,
And it does respond when i use it in another program (seq24)
Any idea, did i overlook something, please help me on the way,
Thanks in advance, Dian from the Netherlands

**Comment by pd-l2ork** [comment]
You usually need to connect MIDI ports (e.g. your hardware port with
pd-l2ork's virtual port). You can use qjackctl or other apps that allowed
those conections to be established. Hope this helps!

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment]
Forgot to mention, if this solves your problem please let us know, so that
we can close this ticket. Thank you.

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by arpeggio1234** [comment]
Yeah man, thanks a lot, offcourse this works, that i did not think off that.
Dian

**Comment by pd-l2ork** [comment]
Glad to hear it worked. Marked as resolved.
