### ISSUE TITLE
Can't build this on Ubuntu past 16.04

### ISSUE THREAD

**Issue by brandflake11** [pd-l2ork/pd#48]
I really, _really_ want to get this version of pd-l2ork running on Ubuntu 18.04, even if I have to leave out certain externals (I can always add different builds later). How would I modify the source of this to get it working on newer linux systems, or is there a way to make the build process work on newer systems than Ubuntu 16.04?

Thank you very much for any and all help on this matter, this is the most stable version of pd I have ever used.

**Comment by jonwwilkes** [comment]
I'd try following the links for the PPAs here:

https://git.purrdata.net/jwilkes/purr-data#downloads

If Pd-l2ork 1.0 is what you're after, I believe Albert has both Pd-l2ork 1.0 and Purr Data available.

**Comment by pd-l2ork** [comment]
Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

---------- Forwarded message ---------
From: Ivica Ico Bukvic <ico@vt.edu>
Date: Fri, Apr 12, 2019, 21:09
Subject: Re: [pd-l2ork/pd] Can't build this on Ubuntu past 16.04 (#48)
To: jonwwilkes <notifications@github.com>


I just recently built Purr-Data on 18.04. Lemme know if you are unable to
locate it elsewhere.

Best,

Ico
On 4/12/2019 8:52 PM, jonwwilkes wrote:

I'd try following the links for the PPAs here:

https://git.purrdata.net/jwilkes/purr-data#downloads

If Pd-l2ork 1.0 is what you're after, I believe Albert has both Pd-l2ork
1.0 and Purr Data available.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pd-l2ork/pd/issues/48#issuecomment-482761950>, or mute
the thread

**Comment by brandflake11** [comment]
I've looked for a build of pd-l2ork 1.0 for newer Ubuntus past 16.04, but they do not exist to my knowledge. Is there anyway I can get a version of 1.0 built, or steps to remove Gem and RTCmix, which I think are the culprits stopping pd-l2ork 1.0 from building on 18.04?

**Comment by jonwwilkes** [comment]
There should be some documentation in l2ork_addons/tar_em_up.sh explaining how to compile without Gem. Not sure about rtcmix-- perhaps look in externals/Makefile

**Comment by pd-l2ork** [comment]
Indeed. There may be also some adjustments to the control file.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by brandflake11** [comment]
Okay, I got the core pd-l2ork 1.0 build, running, and installed, and I am getting the individual externals and extensions copied to their respective folders. Are the extensions and externals the same in purr-data as they are in pd-l2ork 1.0? The tar_em_up.sh script fails, but it does build a significant chunk of everything (while trying to remove the /etc/ folder). I ask because, would it be easier to copy the externals and extensions from purr-data to use with the core pd-l2ork 1.0 build, rather than hunting down the source code and copying them where they should be?

**Comment by jonwwilkes** [comment]
What exactly is the reason you need pd-l2ork 1.0?

There are some public interfaces in Purr Data which don't exist in pd-l2ork 1.0. Mostly this would affect GUI externals-- others should probably work fine.

**Comment by brandflake11** [comment]
I greatly prefer the stability and interface of pd-l2ork 1.0. This program is rock solid and I've had so many weird problems with purr-data on many different purr-data builds and GNU/Linux systems. Pd-l2ork 1.0 was one my greatest tools for getting work done until I upgraded my Ubuntu to 18.04 and I really miss it. I like how scalable purr-data is with its svg features, but pd-l2ork 1.0 is such a stable powerhouse of a program. I hope to see purr-data thrive, but pd-l2ork 1.0 is truly a magnificent program. I also wish it was maintained for newer systems and not seemingly abandoned for purr-data. Not only that, but pd-l2ork 1.0 has K12 mode, which is a fantastic tool for teaching people how to start pd, even though I know you're working hard on this mode for purr-data. Pd-l2ork 1.0 works way faster on my machines as well, another huge bonus of the version.

I will try to see if purr-data's externals will work on pd-l2ork 1.0. Jonathan, I cannot thank you enough for all of your help.

**Comment by brandflake11** [comment]
Okay, I got pd-l2ork 1.0 working and either built the externals that can build properly, or copied some from a cloned Ubuntu 16.04 drive with the built externals on it.  The only thing I cannot get working now is the image object. I can load the object, but then the object disappears and the terminal spits this out: 
```
in sys_gui .x6cae5700.c create image 12 12 -tags 6cb0ebe0S
invalid command name ".x6cae5700.c"
in sys_gui .x6cae5700.c itemconfigure 6cb0ebe0S -image
invalid command name ".x6cae5700.c"
in sys_gui .x6cae5700.c itemconfigure 6cb0ebe0S -image $img6cb0ebe0
invalid command name ".x6cae5700.c"
```
Do you know what this might be about?

**Comment by pd-l2ork** [comment]
I am working on rebuilding now. It appears a number of places throughout
core pd-l2ork and ggee use .x%x.c as opposed to .x%lx.c format. I have this
fixed in my latest source. gem2pdp and rtcmix are broken beyond what I have
time to troubleshoot and am currently trying to merge Gem 0.94. once this
is done I will send you a link to the deb file and update git, so that you
can build it on your own.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment]
OK, try checking out the latest git source and building with ./tar_em_up.sh
-B

It should give you everything, including gem2pdp. Please note this has not
been tested extensively at all. I already know of at least one 3rd-party
library bug lyon/bashfest~ which crashes when given no argument/array name.
This may have been the case before, as well, and I simply did not have a
chance to test it. I have informed Eric of this to see if he may be able to
address it.

Also, note that Gem is stuck at 0.93 with one small fix that allows it to
build on 18.04 Ubuntu. When I tried building 0.94 it would cause pd-l2ork
to segfault at start-up. I emailed IOhannes to see if he may know the
answer.

To be able to build go to
http://l2ork.music.vt.edu/main/make-your-own-l2ork/software/ and install
the supporting libraries. Namely, type:

sudo apt-get install bison flex automake qjackctl tcl8.5-dev tk8.5-dev
tcl-dev tk-dev libasound2-dev libjack-jackd2-dev libtool libbluetooth-dev
libgl1-mesa-dev libglu1-mesa-dev libglew-dev libmagick++-dev libftgl-dev
libgmerlin-dev libgmerlin-avdec-dev libavifile-0.7-dev libmpeg3-dev
libquicktime-dev libv4l-dev libraw1394-dev libdc1394-22-dev libfftw3-dev
libvorbis-dev ladspa-sdk dssi-dev tap-plugins ladspa-foo-plugins
invada-studio-plugins-ladspa blepvco swh-plugins mcp-plugins cmt blop omins
ubuntustudio-audio-plugins rev-plugins liblilv-dev dssi-utils vco-plugins
wah-plugins fil-plugins mda-lv2 libmp3lame-dev libspeex-dev libgsl0-dev
portaudio19-dev python-dev libsmpeg0 libjpeg62 tkpng flite1-dev libgsm1-dev
libfftw3-dev libgtk2.0-dev subversion git libstk0-dev libsndobj-dev
libfluidsynth-dev tclxapian fluid-soundfont-gm python-tk byacc

Hope this helps.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment]
Upon further investigation it appears gem2pdp even though it compiles, fails to create, so I am inclined to let go of that one, as well.

**Comment by brandflake11** [comment]
Wow, thank you so much Ico for this. I am building right now and will report back if I run into errors/problems.

**Comment by agraef** [comment]
Hi Ico, thanks a lot for your work on this! I'll see see that I put pd-l2ork1 back into my PPAs asap, now that it compiles again. I already have that on my TODO list, but it's the beginning of the semester over here, so don't hold your breath just yet. :)
