### ISSUE TITLE
Request for an aur build of pd-l2ork 1.0 for arch linux

### ISSUE THREAD

**Issue by brandflake11** [pd-l2ork/pd#50]
Hello all,

Is there any way to get pd-l2ork 1.0 (the version made with tcl/tk) for arch linux? I have tried to build it from source with errors, and the aur versions do not seem to work well. Some things just do not build, and I do not get a binary of pd-l2ork k12.

Has anyone on this project gotten pd-l2ork 1.0 to work with arch linux?

Thank you very much for your time!

**Comment by agraef** [comment]
Yeah sorry, I let that slip for a bit. I have trouble building it myself. :)
I'm currently working on this (as you might know, I'm the maintainer of the Pd-l2ork/Purr Data packages in the AUR). If you managed to build it, it would be interesting to see your PKGBUILD.

**Comment by agraef** [comment]
Ok, I got this to build and run on Arch again, see #51 for the changes that were needed.

I'm still having big issues with the font sizes. Fiddling a bit with the font selection logic makes the base fonts work, but the IEM GUI font sizes are still *way* off. Screenie:

![image](https://user-images.githubusercontent.com/2853977/62798517-b3967980-bade-11e9-8593-62773df61d9a.png)

Ico, do you have an idea how one might go about fixing the IEM GUI font sizes? I have a high-dpi display which I'm running at 120 dpi currently, but no matter what the particular scaling is, the IEM GUI fonts always appear to be much too large. What gives?

Anyway, that's as far as I got for now. I'm putting this out there for Arch users to try. I've uploaded an updated PKGBUILD for #51 at https://bitbucket.org/agraef/pd-l2ork-pkgbuild (this will go into the AUR once #51 has been merged).

**Comment by agraef** [comment]
@brandflake11 I just went ahead and pushed the pd-l2ork-git PKGBUILD to the AUR, so you should now be able to install it from there with something like `yay -S pd-l2ork-git`. I'll also update the pd-l2ork package and the corresponding binary package later tonight. (The two packages will be identical at this point, so for now it won't matter which one you install. If you prefer a binary package, that should be up at https://l2orkaur.bitbucket.io/ in an hour or so.)

**Comment by agraef** [comment]
All done and dusted. Ubuntu packages for newer Ubuntu versions (19.04, 18.04, maybe 16.04 if it builds there) will be available some time tomorrow.

**Comment by agraef** [comment]
Ico, I just went ahead and merged #51 now. I hope this is ok with you. If not then yell at me. :)

**Comment by pd-l2ork** [comment]
Thanks for that. Please make sure that the wiringpi git is older version
before it prevented static linking.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment]
Also, does this solve the gem issue, as well? Or do I still need to work on
that?

**Comment by brandflake11** [comment]
Woah, I just got the update from my aur helper, and will try this tonight. This is amazing, thank you so much Albert.

**Comment by agraef** [comment]
@brandflake11, you're welcome, let me know how it works for you.

> Please make sure that the wiringpi git is older version before it prevented static linking.

Ico, I'm not sure what version that is, but I only changed the submodule URL from the dysfunctional git://git.drogon.net/wiringPi to Jonathan's mirror at https://git.purrdata.net/jwilkes/wiringPi.git. The submodule hash is still the same commit (AFAICT this is rev. 96344ff7, which is also the revision being used in purr-data), so we should be fine there. Is there an easy way to test that this stuff is actually working, some help patch maybe?

> Also, does this solve the gem issue, as well? Or do I still need to work on that?

Well, you prevented me from doing it my way, so yes, you still have to do that. :) Here's the required change again: https://github.com/agraef/Gem/commit/53e3be2faf3d7d555ddae8f5d97e14449446b1b0

**Comment by pd-l2ork** [comment]
Please feel free to solve it your way :-)

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by agraef** [comment]
Oh dear, I already merged this. Off to another pull request...

**Comment by agraef** [comment]
Done.

**Comment by brandflake11** [comment]
So far, pd-l2ork 1.0 20190811.r1766.bcbaf448-1 is working great! Even gem works, which is super cool! The big text is still a thing in the guis, but this is not a problem for me. I will build the new version 20190812.r1771.42cedfa8-2 sometime later to test as well.

Also, I noticed that rtcmix~ doesn't work anymore. Is this something to do with rtcmix not building?

**Comment by pd-l2ork** [comment]
Thank you, Brandon. Until maintainers fix rtcmix~ upstream including
support for other platforms, it will be unfortunately disabled.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by agraef** [comment]
Hi @brandflake11, thanks for reporting back! If I'm not mistaken, the font size issue should be resolved in r1771.

BTW, packages are now also at the Open Build Service (OBS), at https://build.opensuse.org/package/show/home:aggraef/pd-l2ork. Click on the Download link in the upper right corner, select your OS, and you'll be offered the options to add the package repository (used exactly like a Linux PPA, but also works on plain old Debian) or download packages directly. Likewise the packages for purr-data are available at https://build.opensuse.org/package/show/home:aggraef/purr-data.

No worries, the Launchpad PPAs aren't going away any time soon, I can do both. The big advantage of the OBS is, however, that I can build packages for pretty much every popular Linux distribution out there. Right now I'm concentrating on the Arch- and Debian-based distros, in particular you'll find packages for recent Debian, Raspbian and Ubuntu releases there (Debian/Raspbian Stretch and Buster, Ubuntu Xenial, Bionic and Disco), so as long as you're running these Debian flavors and derivatives (or Arch), we'll have you covered. :) As soon as I find the time to write up the spec files, I will also be able to target the RPM-based distros such as Fedora and OpenSuSE, so that we'll have a package for pretty much everyone running Linux.

I still have to update https://l2orkubuntu.bitbucket.io/ and https://l2orkaur.bitbucket.io/, and write a wiki article about all this, but if you understand how to use the OBS (it's not more difficult that handling PPAs) then you can start using these repos today.

For the user it's pretty much the same, but for a package maintainer the OBS runs circles around Launchpad IMHO. I have proper version control over packages, OBS triggers rebuilds automatically when dependencies change, and I can do everything in the command line. The only advantage of Launchpad is that its build servers are a wee bit faster and that Ubuntu users are more familiar with it.

And the acronym. Not very Google-friendly. But I think that OBS = Open Build Service is actually pretty old, it must have come way before the OBS = Open Broadcaster Studio we all know and love. :)

**Comment by agraef** [comment]
Sorry, I forgot that you're on Arch now. Well, then the font size issue should be mitigated with r1771 as well, although it won't look quite as nice as on Ubuntu. But there's hope that Ubuntu will eventually catch up to present-day Arch and Ico will run into the same issue there, and fix it. :)

Also, here's the new and shiny binary pacman repo on OBS (contains also all necessary dependencies): https://build.opensuse.org/package/show/home:aggraef:arch/pd-l2ork

**Comment by brandflake11** [comment]
Alright, the newer version fixed the font size issue, it is not exactly as it was, but it is pretty close to the same. Also Albert, I wanted to report that pd-l2ork 1.0 builds successfully also on pentium4-based Arch32 computers, which is now an Arch32 package architecture. I have an old netbook with an up to date Arch32 that this new pd-l2ork build works great on. Also, I cannot thank you enough.

**Comment by agraef** [comment]
@brandflake11 thanks for the heads up about the x86 build.

The OBS packages are now at https://build.opensuse.org/project/show/home:aggraef (together with all the Debian/Ubuntu packages), with installation instructions over at my [purr-data wiki](https://github.com/agraef/purr-data/wiki/Installation#arch) -- they also apply to pd-l2ork which I offer in the same repo (which is 64 bit only, though, OBS doesn't support 32 bit builds on Arch any more). Well, I guess that people running older x86 computers or netbooks can either grab my PKGBUILD from the AUR and use makepkg, or install straight from the source, as you did.

P.S.: Ico, as you can see, I also have pd-l2ork for a whole bunch of different recent Debian and Ubuntu releases there now, including Debian Sid/Buster/Stretch and Ubuntu 19.04/18.04/16.04. So if someone asks you for a Debian/Ubuntu package of pd-l2ork, you can just point them to my repo and my installation guide. :)

I also started work on RPM-based distributions (openSUSE, specifically, which is fairly popular over here in Europe; Fedora will follow later). I already ported purr-data to openSUSE, which was quite easy. So pd-l2ork shouldn't be a big deal either, but I first need to port tkpng and xapian-tcl-bindings which unfortunately aren't in the openSUSE repositories anywhere.

**Comment by agraef** [comment]
Yeah, makes it much easier, doesn't it? ;-) In fact, since I started using Arch a few years ago, I'm relying a *lot* on Arch PKGBUILDs (both in the official repos and the AUR) to figure out how stuff is supposed to be built, especially if I'm on another distro like Ubuntu.

**Comment by brandflake11** [comment]
Yes, the AUR is a godsend; Arch is a true community effort! Keep doing your thing Albert!
